apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  generation: 1
  labels:
    app: "{{ .Values.jenkins.name }}"
  name: "{{ .Values.jenkins.name }}"
  namespace: default

spec:
  progressDeadlineSeconds: 600
  replicas: {{ .Values.jenkins.replicaCount }}
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: "{{ .Values.jenkins.name }}"
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: "{{ .Values.jenkins.name }}"
    spec:
      containers:
      - image: "{{ .Values.jenkins.image }}"
        imagePullPolicy: "{{ .Values.jenkins.pullPolicy }}"
        name: jenkins-core
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
