---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "{{ .Values.jira.name }}-endpoint"
  namespace: "{{ .Values.namespace }}"
  labels:
    app: {{ .Values.jira.name }}
spec:
  ports:
  - protocol: "TCP"
    port: {{ .Values.jira.maptoport }}
    targetPort: {{ .Values.jira.port }}
  selector:
    app: {{ .Values.jira.name }}
  type: "{{ .Values.jira.iptype }}"
  loadBalancerIP: ""