---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "{{ .Values.jenkins.name }}-endpoint"
  namespace: "{{ .Values.namespace }}"
  labels:
    app: {{ .Values.jenkins.name }}
spec:
  ports:
  - protocol: "TCP"
    port: {{ .Values.jenkins.maptoport }}
    targetPort: {{ .Values.jenkins.port }}
  selector:
    app: {{ .Values.jenkins.name }}
  type: "{{ .Values.jenkins.iptype }}"
  loadBalancerIP: ""
