---
apiVersion: "app.k8s.io/v1beta1"
kind: Application
metadata:
  name: "{{ .Release.Name }}"
  annotations:
    kubernetes-engine.cloud.google.com/icon: >-
  labels:
    app.kubernetes.io/name: "{{ .Release.Name }}"
spec:
  descriptor:
    version: '7.6'
    type: sonarqube
    description: |-
      sonarqube is Ticketing tool

      Identify HTTPS endpoint.

      ```shell
      echo https://$(kubectl -n{{ .Release.Namespace }} get ingress -l "app.kubernetes.io/name={{ .Release.Name }}" -ojsonpath="{.items[0].status.loadBalancer.ingress[0].ip}")/
      ```

      For HTTPS you have to accept a certificate (we created a temporary one for you). Now you need a password.

      ```shell
      kubectl -n{{ .Release.Namespace }} exec \
        $(kubectl -n{{ .Release.Namespace }} get pod -oname | sed -n /\\/{{ .Release.Name }}-jenkins/s.pods\\?/..p) \
      ```
  info:
  - name: sonarqube HTTPS URI
    type: Reference
    valueFrom:
      ingressRef:
        name: "{{ .Release.Name }}-sonarqube-ui"
        protocol: HTTPS
  selector:
    matchLabels:
      app.kubernetes.io/name: "{{ .Release.Name }}"
  componentKinds:
  - group: v1
    kind: PersistentVolumeClaim
  - group: v1
    kind: Secret
  - group: v1
    kind: Service
  - group: apps/v1beta2
    kind: StatefulSet
  - group: extensions/v1beta1
    kind: Ingress

