# This is a basic workflow to help you get started with Actions

name: CopyFile2S3

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  pull_request:
    branches: [ master ]

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      with:
        ref: 'master'
    
    - name: Install AWS CLI
      run: "sudo apt update -y ; sudo apt install -y awscli"
    
    - name: Connect AWS and List Buckets
      run: |
        aws configure set aws_access_key_id ${{ secrets.ACCESSID }}
        aws configure set aws_secret_access_key ${{ secrets.SECRETKEY }}
        aws s3 ls
        echo "Listing Files"
        ls $GITHUB_WORKSPACE -latr
        aws s3 sync oneclickdeploy s3://ashishbucketpoc/oneclickdeploy/

